CREATE TABLE Account (
	username VARCHAR(20) PRIMARY KEY,
	password CHAR(64) NOT NULL,
	salt CHAR(8) NOT NULL
);

CREATE TABLE Picture (
	id SERIAL PRIMARY KEY,
	uploaded TIMESTAMP NOT NULL DEFAULT NOW(),
	ownedby VARCHAR(20)
		REFERENCES Account (username)
		ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE Comment (
	id SERIAL PRIMARY KEY,
	content TEXT NOT NULL,
	picture INTEGER NOT NULL
		REFERENCES Picture (id)
		ON UPDATE CASCADE ON DELETE CASCADE,
	parent INTEGER,
	byuser VARCHAR(20)
		REFERENCES Account (username)
		ON UPDATE CASCADE ON DELETE SET NULL,
	posted TIMESTAMP NOT NULL DEFAULT NOW(),
	edited BOOLEAN NOT NULL DEFAULT FALSE,
	FOREIGN KEY (parent) REFERENCES Comment (id)
		ON UPDATE CASCADE ON DELETE CASCADE
);

